#!/bin/sh

# TODO should probably check this is macos

sudo touch /etc/pam.d/sudo_local
sudo tee -a /etc/pam.d/sudo_local >/dev/null <<-EOF
# sudo_local: local config file which survives system update and is included for sudo
# uncomment following line to enable Touch ID for sudo
auth       sufficient     pam_tid.so
EOF

sudo chmod 444 /etc/pam.d/sudo_local
